title: "3D Medical Image Representation and Rendering(3DMIRR)"
email: "asheibanifard@bournemouth.ac.uk"
description: "This page is dedicated to 3D medical image representaion and rendering using variable rendering techniques. A collection of SOTA works in this field to keep the user update"
baseurl: ""
url: "https://asheibanifard.github.io/" # Replace with your URL
 # You can change this to another theme later

# Navigation links
navbar:
  - title: "Home"
    url: "/"
  - title: "NeuroHub"
    url: "/neurohub/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"

# Exclude these from processing
exclude:
  - Gemfile
  - Gemfile.lock

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: assets/css
  style: compressed
